### ISSUE TITLE
Password?

### ISSUE THREAD

**Issue by koesherbacon** [Newt-OS/Newt-OS#1]
I'm trying to test out your Newt Loki, but I can't login to the live system. Can you tell me the password? Thanks a lot!

**Comment by koesherbacon** [comment]
Please disregard. I found it.  If anyone else is having this problem bc its only shown in the SuseStudio page, not the webly one, it's "newts" w/o quotes.

**Comment by paulogaucho22** [comment]
para mim não está funcionando, vou desistir de conhecer( sem senha)
